# Generated by Django 3.1 on 2020-09-28 20:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoStainerStation',
            fields=[
                ('autostainer_sn', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('latest_sync_time_PA', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommonReagent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reag_name', models.TextField(blank=True)),
                ('size', models.TextField(default='S')),
                ('log', models.TextField(blank=True)),
                ('vol', models.IntegerField(verbose_name=3000)),
                ('vol_cur', models.IntegerField(verbose_name=3000)),
                ('sequence', models.IntegerField(blank=True)),
                ('mfg_date', models.DateField(blank=True)),
                ('exp_date', models.DateField(blank=True)),
                ('date', models.DateTimeField(blank=True)),
                ('r_type', models.TextField(blank=True)),
                ('factory', models.BooleanField(default=False)),
                ('autostainer_sn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reagents.autostainerstation')),
            ],
        ),
        migrations.CreateModel(
            name='PA',
            fields=[
                ('fullname', models.TextField(blank=True)),
                ('alias', models.TextField(blank=True)),
                ('source', models.TextField(blank=True)),
                ('volume', models.IntegerField(default=0)),
                ('incub', models.IntegerField(default=15)),
                ('ar', models.TextField(default='NO')),
                ('description', models.TextField(blank=True)),
                ('is_factory', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('catalog', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reagent',
            fields=[
                ('commonreagent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='reagents.commonreagent')),
                ('reagent_sn', models.TextField(primary_key=True, serialize=False)),
            ],
            bases=('reagents.commonreagent',),
        ),
        migrations.CreateModel(
            name='ReagentDelta',
            fields=[
                ('commonreagent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reagents.commonreagent')),
                ('reagent_sn', models.TextField()),
                ('operation', models.TextField()),
            ],
            bases=('reagents.commonreagent',),
        ),
        migrations.CreateModel(
            name='PADelta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.TextField(blank=True)),
                ('alias', models.TextField(blank=True)),
                ('source', models.TextField(blank=True)),
                ('volume', models.IntegerField(default=0)),
                ('incub', models.IntegerField(default=15)),
                ('ar', models.TextField(default='NO')),
                ('description', models.TextField(blank=True)),
                ('is_factory', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('catalog', models.TextField()),
                ('operation', models.TextField()),
                ('autostainer_sn', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reagents.autostainerstation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='commonreagent',
            name='catalog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reagents.pa'),
        ),
    ]
