# Generated by Django 3.1 on 2020-09-17 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reagents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pa',
            name='alias',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pa',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pa',
            name='fullname',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pa',
            name='source',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='padelta',
            name='alias',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='padelta',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='padelta',
            name='fullname',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='padelta',
            name='source',
            field=models.TextField(blank=True),
        ),
    ]
