# Generated by Django 3.1 on 2020-09-18 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reagents', '0002_auto_20200917_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padelta',
            name='autostainer_sn',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reagents.autostainerstation'),
        ),
    ]
