# guide from https://realpython.com/django-development-with-docker-compose-and-machine/
version: '3.8'

services:
  web:
    restart: always
    build: ./web
    ports:
      - "8000:8000"
    links:
      - postgres:postgres
    volumes:
      - web-reagentdb:/usr/src/app
      - web-static:/usr/src/app/static
    env_file:
      - .env
    environment:
      DEBUG: 'true'
    #command: /usr/local/bin/gunicorn ReagentDB.wsgi:application -w 2 -b :8000
    command: /usr/local/bin/gunicorn --workers=2 --bind 0.0.0.0:8000 ReagentDB.wsgi:application

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - web-static:/www/static
    links:
      - web:web
    depends_on:
      - web

  postgres:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust" # new

volumes:
  web-reagentdb:
  web-static:
  pgdata: