# guide from https://realpython.com/django-development-with-docker-compose-and-machine/
# and also https://github.com/testdrivenio/django-on-docker
version: '3.8'

services:
  web:
    restart: always
    build:
      context: ./app
      dockerfile: Dockerfile
    #command: python manage.py runserver 0.0.0.0:8000
    command: >
      sh -c "python manage.py testserver --addrport 0.0.0.0:8000
      ./reagents/fixtures/test_pa.json
      ./reagents/fixtures/test_autostainerstation.json
      ./reagents/fixtures/test_pa_delta.json
      ./reagents/fixtures/test_users.json
      --noinput"
    ports:
      - "8000:8000"
    volumes:
      - ./app/:/usr/src/app/
    env_file:
      - ./.env.dev
    depends_on:
      - postgres

  postgres:
    image: postgres:12.4-alpine
    volumes:
      - ./pgdata:/var/lib/postgresql_test/data/
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust # new
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres_dev
      - POSTGRES_HOST=postgres

volumes:
  pgdata: