version: '3.8'

services:
  reagentdb:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    #image: caxcheun/reagentsdb:v0.1
    command: gunicorn ReagentDB.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/reagentdb/static
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - postgres
  
  postgres:
    image: postgres:12.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/reagentdb/static
    ports:
      - 8000:8000
      - 80:80
    depends_on:
      - reagentdb

volumes:
  postgres_data:
  static_volume: