# guide from https://realpython.com/django-development-with-docker-compose-and-machine/
# and also https://github.com/testdrivenio/django-on-docker
version: '3.8'

services:
  web:
    restart: always
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./app/:/usr/src/app/
    env_file:
      - ./.env.dev
    depends_on:
      - postgres

  postgres:
    image: postgres:12.4-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust" # new
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres_dev

volumes:
  pgdata: