# ReagentDB v0.3
version: '3.8'

services:
  reagentdb:
    image: reagentsdb:v0.3
    restart: always
    command: /home/app/reagentdb/entrypoint.prod.sh
    volumes:
      - static_volume:/home/app/reagentdb/static
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - postgres
      - redis

  reagentdbws:
    restart: always
    image: reagentsdb:v0.3
    entrypoint: /home/app/reagentdb/entrypoint.ws-prod.sh
    volumes:
      - static_volume:/home/app/reagentdb/static
    expose:
      - 9000
    env_file:
      - ./.env.prod
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:12.4-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
      
  redis:
    restart: always
    image: redis:5.0-alpine

  celery:
    restart: always
    image: reagentsdb:v0.3
    command: celery -A ReagentDB worker -l info
    volumes_from:
      - reagentdb
    env_file:
      - ./.env.prod
    depends_on:
      - reagentdb

  celery-beat:
    restart: always
    image: reagentsdb:v0.3
    command: celery -A ReagentDB beat -l info
    volumes_from:
      - reagentdb
    env_file:
      - ./.env.prod
    depends_on: 
      - reagentdb

  nginx:
    restart: always
    image: nginx:1.19.2-alpine
    volumes:
      - static_volume:/home/app/reagentdb/static
    ports:
      - 8000:8000
      - 80:80
    depends_on:
      - reagentdb

volumes:
  postgres_data:
  static_volume: