# ReagentDB v0.1
version: '3.8'

services:
  reagentdb:
    image: reagentsdb:v0.1
    command: gunicorn ReagentDB.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/reagentdb/static
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - postgres
      - redis
  
  postgres:
    image: postgres:12.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
      
  redis:
    image: redis:6.0-alpine

  celery:
    image: reagentsdb:v0.1
    command: celery -A ReagentDB worker -l info
    volumes_from:
      - reagentdb
    env_file:
      - ./.env.prod
    depends_on:
      - reagentdb

  celery-beat:
    image: reagentsdb:v0.1
    command: celery -A ReagentDB beat -l info
    volumes_from:
      - reagentdb
    env_file:
      - ./.env.prod
    depends_on: 
      - reagentdb

  nginx:
    image: nginx:1.19.2-alpine
    volumes:
      - static_volume:/home/app/reagentdb/static
    ports:
      - 8000:8000
      - 80:80
    depends_on:
      - reagentdb

volumes:
  postgres_data:
  static_volume: