# TODO: Figure out how to tag locally created images
# Sample docker-compose.yml that will be given to customers, along with
# the .tar images so they only need to install docker, and not create an
# account
version: '3.8'

services:
  reagentdb:
    image: reagentdb_reagentdb
    command: gunicorn ReagentDB.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/reagentdb/static
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - postgres
  
  postgres:
    image: postgres:12.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    
  nginx:
    image: reagentdb_nginx
    volumes:
      - static_volume:/home/app/reagentdb/static
    ports:
      - 8000:8000
      - 80:80
    depends_on:
      - reagentdb

volumes:
  postgres_data:
  static_volume: