# Generated by Django 3.1 on 2020-08-12 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoStainerStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.TextField()),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reagent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reag_name', models.TextField()),
                ('catalog', models.TextField()),
                ('type', models.TextField()),
                ('size', models.TextField()),
                ('sn', models.TextField()),
                ('log', models.TextField()),
                ('vol', models.IntegerField()),
                ('mfg_date', models.IntegerField()),
                ('exp_date', models.IntegerField()),
                ('factory', models.IntegerField()),
                ('vol_cur', models.IntegerField()),
                ('sequence', models.IntegerField()),
                ('edit_date', models.IntegerField()),
                ('reserved', models.IntegerField()),
                ('owned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reagents.autostainerstation')),
            ],
        ),
    ]
