# Generated by Django 3.1 on 2020-08-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reagents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pa',
            name='catalog',
            field=models.TextField(blank=True, unique=True),
        ),
    ]
