# Generated by Django 3.1 on 2020-08-24 15:37

# TODO: refer https://dev.to/guin/writing-a-django-data-migration-with-real-world-example-40m to make a 
# migration that will contain a prepopulated database

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reagents', '0001_initial'),
    ]

    operations = [
    ]
