# Generated by Django 3.1 on 2020-09-03 18:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reagents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pa',
            options={},
        ),
        migrations.RemoveField(
            model_name='padelta',
            name='update_at',
        ),
        migrations.AddField(
            model_name='padelta',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
