# Generated by Django 3.1 on 2020-08-31 20:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reagents', '0002_auto_20200824_0837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pa',
            name='factory',
        ),
        migrations.RemoveField(
            model_name='pa',
            name='id',
        ),
        migrations.AddField(
            model_name='autostainerstation',
            name='latest_sync_time_PA',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pa',
            name='catalog',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='PADelta',
            fields=[
                ('fullname', models.TextField()),
                ('alias', models.TextField()),
                ('source', models.TextField()),
                ('catalog', models.TextField(primary_key=True, serialize=False)),
                ('volume', models.IntegerField(default=0)),
                ('incub', models.IntegerField()),
                ('ar', models.TextField()),
                ('description', models.TextField()),
                ('is_factory', models.BooleanField(default=False)),
                ('operation', models.TextField()),
                ('update_at', models.DateField()),
                ('update_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reagents.autostainerstation')),
            ],
        ),
    ]
