# Generated by Django 3.1 on 2020-08-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reagents', '0002_auto_20200818_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pa',
            name='volume',
            field=models.IntegerField(default=0),
        ),
    ]
