# Generated by Django 3.1 on 2020-08-20 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reagents', '0003_auto_20200819_0853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autostainerstation',
            old_name='sn',
            new_name='autostainer_sn',
        ),
        migrations.RenameField(
            model_name='reagent',
            old_name='owned_by',
            new_name='autostainer_sn',
        ),
        migrations.RenameField(
            model_name='reagent',
            old_name='sn',
            new_name='reagent_sn',
        ),
        migrations.AlterField(
            model_name='pa',
            name='factory',
            field=models.IntegerField(default=1),
        ),
    ]
