# Generated by Django 3.1 on 2020-08-20 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reagents', '0004_auto_20200820_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reagent',
            old_name='type',
            new_name='r_type',
        ),
    ]
